# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [23]:
import numpy as np

arr = np.random.randint( 1, 20, (5,5))
arr[:, 2:3] = 1
print(arr)

arr2 = np.random.randint(1, 16, (4,4))
arr2[0:1,0:1] = 0
arr2[1:2,1:2] = 0
arr2[2:3,2:3] = 0
arr2[3:4,3:4] = 0
print(arr2)

[[ 9  8  1 18 17]
 [ 5 16  1  2  7]
 [12 12  1 10 11]
 [19  3  1  1 10]
 [ 8 12  1 14 18]]
[[ 0 12  5  3]
 [12  0 15  9]
 [ 6  6  0 10]
 [ 7 10 15  0]]


In [36]:
np.random.seed(42)
arr = np.random.randint(1, 36, (6,6))
arr[3:6, 2:5]


arr = np.random.randint(0, 5, (5,5))

array([[3, 3, 3, 3, 4],
       [2, 0, 3, 1, 3],
       [1, 1, 3, 4, 1],
       [1, 3, 1, 1, 3],
       [3, 0, 4, 4, 1]], dtype=int32)

In [41]:
np.random.seed(42)
arr1 = np.random.randint(1, 10, (3,4))
arr2 = np.random.randint(1, 10, (3,4))

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

arr3 = np.random.randint(1, 16, (4,4))
print(arr3)
print(np.sum(arr3, axis=0))
print(np.sum(arr3, axis=1))

[[10 10 13  7]
 [15  9  9 13]
 [ 6 10 17  9]]
[[ 4 -2  3  3]
 [-1 -3  5  3]
 [ 4 -2 -1  7]]
[[21 24 40 10]
 [56 18 14 40]
 [ 5 24 72  8]]
[[2.33333333 0.66666667 1.6        2.5       ]
 [0.875      0.5        3.5        1.6       ]
 [5.         0.66666667 0.88888889 8.        ]]
[[11 11 15 10]
 [12 12 15 14]
 [14 15 14  3]
 [12  7  4  9]]
[49 45 48 36]
[47 53 46 32]


In [43]:
arr = np.random.randint(1, 10, (5,5))

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

new_arr = np.random.randint(1, 9, (3,3))

# normalization (arr * mean) / std
mean = np.mean(new_arr)
std = np.std(new_arr)

normalized_arr = (new_arr - mean) / std
print(normalized_arr)

5.92
7.0
2.7410946718418905
7.5136
[[-1.13137085  1.83847763 -0.28284271]
 [-0.28284271 -1.13137085 -0.28284271]
 [ 0.56568542 -0.70710678  1.41421356]]


In [46]:
arr1 = np.random.randint(1, 9, (3,3))
arr2 = np.array([1,2,3])
print(arr1)
print(arr2)
print(arr1 + arr2)

[[6 3 3]
 [1 3 5]
 [7 6 3]]
[1 2 3]
[[7 5 6]
 [2 5 8]
 [8 8 6]]
